name: Documentation CI
on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  pages: write

jobs:
  docs:
    uses: kordlib/.teamcity/.github/workflows/wiki.yml@main
    with:
      path: docs/kord
      product: KORD
      algolia-index: kord_wiki
      version: 0.14.0
    secrets:
      algolia-token: '${{ secrets.ALGOLIA_KEY }}'
